source("replication.R")

#
# patternCount tests
#
input <- read.delim("dataset_2_7.txt", header = F, stringsAsFactors = F)
text <- input[1,1]
pattern <- input[2,1]

patternCount(text, pattern) == 32


#
# Frequent words test
#
text <- "CGGAAGCGAGATTCGCGTGGCGTGATTCCGGCGGGCGTGGAGAAGCGAGATTCATTCAAGCCGGGAGGCGTGGCGTGGCGTGGCGTGCGGATTCAAGCCGGCGGGCGTGATTCGAGCGGCGGATTCGAGATTCCGGGCGTGCGGGCGTGAAGCGCGTGGAGGAGGCGTGGCGTGCGGGAGGAGAAGCGAGAAGCCGGATTCAAGCAAGCATTCCGGCGGGAGATTCGCGTGGAGGCGTGGAGGCGTGGAGGCGTGCGGCGGGAGATTCAAGCCGGATTCGCGTGGAGAAGCGAGAAGCGCGTGCGGAAGCGAGGAGGAGAAGCATTCGCGTGATTCCGGGAGATTCAAGCATTCGCGTGCGGCGGGAGATTCAAGCGAGGAGGCGTGAAGCAAGCAAGCAAGCGCGTGGCGTGCGGCGGGAGAAGCAAGCGCGTGATTCGAGCGGGCGTGCGGAAGCGAGCGG"
k <- 12
output <- c("CGGCGGGAGATT", "CGGGAGATTCAA", "CGTGCGGCGGGA", "CGTGGAGGCGTG", "CGTGGCGTGCGG",
            "GCGTGCGGCGGG", "GCGTGGAGGCGT", "GCGTGGCGTGCG", "GGAGAAGCGAGA", "GGAGATTCAAGC",
            "GGCGGGAGATTC", "GGGAGATTCAAG", "GTGCGGCGGGAG", "TGCGGCGGGAGA")
res <- frequentWords(text, k)
all(res %in% output) && length(res)==length(output)

text <- "GCGCTTACTAATGCGGGGTAATGCGGGGTATTTACGTGATGCGGGGTAGCGCTTACTAAACTTTCTTCCCGTTGCAGAACTTTCTTCGCGCTTACTAAACTTTCTTCATGCGGGGTAATGCGGGGTAATGCGGGGTAAACTTTCTTCTTTACGTGATGCGGGGTAAACTTTCTTCAACTTTCTTCAACTTTCTTCCCGTTGCAGCCGTTGCAGGCGCTTACTACCGTTGCAGAACTTTCTTCTTTACGTGGCGCTTACTACCGTTGCAGCCGTTGCAGATGCGGGGTAAACTTTCTTCTTTACGTGCCGTTGCAGAACTTTCTTCATGCGGGGTATTTACGTGCCGTTGCAGATGCGGGGTAGCGCTTACTATTTACGTGAACTTTCTTCATGCGGGGTAATGCGGGGTATTTACGTGAACTTTCTTCGCGCTTACTACCGTTGCAGCCGTTGCAGATGCGGGGTAAACTTTCTTCATGCGGGGTACCGTTGCAGCCGTTGCAGTTTACGTGCCGTTGCAGCCGTTGCAGAACTTTCTTCATGCGGGGTATTTACGTGGCGCTTACTAGCGCTTACTAATGCGGGGTAGCGCTTACTAATGCGGGGTAATGCGGGGTATTTACGTGCCGTTGCAGGCGCTTACTACCGTTGCAGATGCGGGGTACCGTTGCAGAACTTTCTTCTTTACGTGCCGTTGCAGGCGCTTACTACCGTTGCAGAACTTTCTTCTTTACGTGCCGTTGCAGGCGCTTACTAATGCGGGGTATTTACGTGGCGCTTACTAATGCGGGGTAATGCGGGGTAAACTTTCTTCATGCGGGGTATTTACGTGTTTACGTGCCGTTGCAGATGCGGGGTACCGTTGCAGATGCGGGGTAAACTTTCTTCAACTTTCTTCCCGTTGCAGTTTACGTGGCGCTTACTATTTACGTGCCGTTGCAGAACTTTCTTC"
k <- 12
res <- frequentWords(text, k)
res
